### ISSUE TITLE
Flutter App will crash

### ISSUE THREAD

**Issue by Jerry92-Lee** [signalfx/splunk-otel-android#284]
When I try to use it in the flutter project, the flutter app will crash with a white screen and the console will output the following error:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/26290419/168039761-c6c04fa5-aa46-4c46-aea8-5977d617d8d8.png">

**Comment by mateuszrzeszutek** [comment]
Hey @Jerry92-Lee ,
Does that happen without splunk-otel-android too? What version of splunk-otel-android are you using?
I have never seen that localhost connection error before, is that something specific to flutter? Can you provide a reproduction scenario (e.g. a simple app that fails this way)?

**Comment by mateuszrzeszutek** [comment]
Hey @Jerry92-Lee ,
Please reopen or create a new issue if you're still encountering this problem.
