### ISSUE TITLE
Support for Retrofit

### ISSUE THREAD

**Issue by scheler** [signalfx/splunk-otel-android#289]
Does this agent support auto-instrumentation of [retrofit](https://square.github.io/retrofit/) http client library?

**Comment by mateuszrzeszutek** [comment]
Hey @scheler ,
We don't have a dedicated instrumentation for retrofit; but we do instrument OkHttp, which is used internally by retrofit. You should be able to instrument your retrofit-based clients by setting a custom OkHttp `Call.Factory`:
```java
new Retrofit.Builder()
  .callFactory(splunkRum.createRumOkHttpCallFactory(new OkHttpClient())
  .build();
```

**Comment by ber4444** [comment]
Do you automatically log network exceptions or only response codes?

**Comment by mateuszrzeszutek** [comment]
We capture all exceptions thrown by the OkHTTP client -- if it throws `SSLHandshakeException` then yes, the telemetry produced by this library will reflect that.

**Comment by ber4444** [comment]
<img width="983" alt="Screen Shot 2022-07-06 at 11 04 11 AM" src="https://user-images.githubusercontent.com/205867/177614555-6b655d53-907d-4949-b2fb-f24110b49f4c.png">
there is a space for network exceptions on the SignalFX UI but nothing gets populated there, so only error codes like HTTP 500 are logged... I think something must be broken that drops cached exceptions in unhealthy network conditions

**Comment by ber4444** [comment]
basically, we need a manual `SplunkRum.getInstance().addRumException(t)` for any exception (we have configured `.crashReportingEnabled(false)` because we use Crashlytics to track crashes but that should not disable logging of non-fatal exceptions).

**Comment by ber4444** [comment]
I just don't see network exceptions captured in practice, so it may be a broken feature

**Comment by mateuszrzeszutek** [comment]
Can you share a reproduction scenario for your use case? It can be a small example app, or a unit test, anything executable. If you're not able to do that, or do not want to share your code publicly, I suggest talking to your Splunk sales rep about your issues - we'll handle this in an internal ticket.

**Comment by ber4444** [comment]
I do see "Network Errors" populated now, thanks for the help
