### ISSUE TITLE
why do you use Splunk

### ISSUE THREAD

**Issue by fizz12344321** [signalfx/splunk-otel-android#307]
Hi, i am reading your repository and i love it, but i have a question, why do you use Splunk ? Can u tell me your purpose, the pros and cons of Splunk, why don't u use Micrometer, Prometheus, grafana. Thank u so much

**Comment by mateuszrzeszutek** [comment]
Hi @fizz12344321 ,
We use Splunk because we *are* Splunk - this project, and every other project in the `signalfx` GitHub organization, are Splunk products.
