### ISSUE TITLE
How to send spans to `jaeger`

### ISSUE THREAD

**Issue by ankitnayan** [signalfx/splunk-otel-android#308]
What changes will be needed to make `splunk-otel-android` send data to jaeger? I see the readme mention something like below

```
    private final Config config = SplunkRum.newConfigBuilder()
            .realm(realm)
            .rumAccessToken(rumAccessToken)
            .applicationName("My Android App")
            .build();
```

**Comment by mateuszrzeszutek** [comment]
Hey @ankitnayan ,
We do not offer a simple, out-of-the-box way to replace the span exporter. This project was built with Zipkin in mind.
You could probably fork this repo (it's open source after all) and apply the changes you need in your own copy.

**Comment by mateuszrzeszutek** [comment]
I'm closing this issue -- please reopen or open a new one if you have any remaining questions.
