### ISSUE TITLE
[GDI Spec] GH Releases MUST use signed tags

### ISSUE THREAD

**Issue by pellared** [signalfx/splunk-otel-android#345]
Per https://github.com/signalfx/gdi-specification/blob/v1.4.0/specification/repository.md?plain=1#L130

> MUST use signed tags

Currently, no [GH Release](https://github.com/signalfx/splunk-otel-android/releases) has a signed tag.

Do you have some releasing docs or script to avoid such problems for future releases? Example from our Go distro: https://github.com/signalfx/splunk-otel-go/blob/main/RELEASING.md

**Comment by mateuszrzeszutek** [comment]
Wait, I can see almost all of the tags in this repo as signed:
![Screen Shot 2022-09-05 at 08 35 39](https://user-images.githubusercontent.com/69198463/188379568-cea39c4f-848f-4278-a718-4c8dc68fade5.png)

How do you verify this?

**Comment by pellared** [comment]
The commit is signed. But the tag is not. See: https://github.com/signalfx/splunk-otel-android/releases/

<img width="174" alt="image" src="https://user-images.githubusercontent.com/5067549/188395086-3acf00d1-27fd-463a-89fd-70c73a135f10.png">

Here is a GitHub Release with a tag signed as well: https://github.com/signalfx/splunk-otel-go/releases

<img width="150" alt="image" src="https://user-images.githubusercontent.com/5067549/188395291-babec932-ad3d-406b-835e-55c0f262da47.png">

**Comment by pellared** [comment]
Also  if you hover over "Verfied" here https://github.com/signalfx/splunk-otel-android/tags and there https://github.com/signalfx/splunk-otel-go/tags then you get different info (signed commit vs signed tag). The UI is confusing. I also remember something like "Partially verified" in GitHub web UI (I am not sure if this label still exists).

**Comment by mateuszrzeszutek** [comment]
Yeah that's super confusing. Thanks for explaining this 👍

**Comment by mateuszrzeszutek** [comment]
I signed and recreated all the tags; PTAL.
(Don't close the issue yet, I'll close it when I add a release script that encapsulates the tag signing)

**Comment by pellared** [comment]
LGTM
