### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by ssidhu-apm** [signalfx/splunk-otel-android#367]
**How can I profile my app in Android Studio with Splunk RUM enabled?**
Splunk RUM uses gzip encoding to reduce network bandwidth consumption. Android Studio's Network Inspector attempts to read the body of the http request and breaks the gzip encoding; which results in 400 responses from our ingest servers. 

As a workaround, you can disable Splunk RUM while profiling your app, or you can disable the gzip compression at the time of profiling your app. 

To learn more please review: https://issuetracker.google.com/issues/200699798 and https://issuetracker.google.com/issues/200852831

**Comment by breedx-splk** [comment]
Thanks @ssidhu-apm . 

I also think that including the error phrase can help people who might be encountering the bug in Android Studio: `error handling gzip compressed request EOF`.  I like this idea of starting up a FAQ for users though.

**Comment by ssidhu-apm** [comment]
How about this?:

Why do I see "error handling gzip compressed request EOF" in Android Studio when I include Splunk RUM?
Splunk RUM uses gzip encoding to reduce network bandwidth consumption. Android Studio's Network Inspector attempts to read the body of the http request and breaks the gzip encoding; which results in 400 responses from our ingest servers.

As a workaround, you can disable Splunk RUM while profiling your app, or you can disable the gzip compression at the time of profiling your app.

To learn more please review: https://issuetracker.google.com/issues/200699798 and https://issuetracker.google.com/issues/200852831
