### ISSUE TITLE
How to get the location?

### ISSUE THREAD

**Issue by ccoqueiro** [signalfx/splunk-otel-android#446]
How to get the location of the device (where the monitored application is running)? Is this information obtained automatically or is there a need for any information?

**Comment by mateuszrzeszutek** [comment]
Hey @ccoqueiro ,

You can pass the location to the Splunk RUM library by calling `SplunkRum#updateLocation()`: https://github.com/signalfx/splunk-otel-android/blob/387b4d88adf2e75b041cb220d3de20a72f0f2370/splunk-otel-android/src/main/java/com/splunk/rum/SplunkRum.java#L309-L318

You can obtain `Location` from the [Android SDK](https://developer.android.com/training/location). The Splunk RUM lib does not retrieve location automatically, we've left that to the users (some apps might already be doing that, some don't use location at all).
