### ISSUE TITLE
Release 1.1.0 is unusable due to missing aar & module artifacts

### ISSUE THREAD

**Issue by ibevilinc** [signalfx/splunk-otel-android#631]
The latest 1.1.0 release on maven central is missing the aar & module artifacts which leads to build failures since there's no library to compile against. Attached are screenshots of the available artifacts between versions 1.0.0 & 1.1.0

<img width="800" alt="1 0 0-artifacts" src="https://github.com/signalfx/splunk-otel-android/assets/1529805/1de39635-f2e2-4ead-b868-6cf657ebfb34">
<img width="838" alt="1 1 0-artifacts" src="https://github.com/signalfx/splunk-otel-android/assets/1529805/48ebbfd2-3c00-450e-bfb2-fac02a91f024">

**Comment by breedx-splk** [comment]
Yes thanks @ibevilinc  -- we caught this last week and released patch [v1.1.1](https://github.com/signalfx/splunk-otel-android/releases/tag/v1.1.1) to fix. Sorry for the hassle.
