### ISSUE TITLE
Vulnerabilities reported on dynamic scan of the app

### ISSUE THREAD

**Issue by ber4444** [signalfx/splunk-otel-android#653]
- make sure https://rum-ingest.us0.signalfx.com/ will set the HTTP Strict Transport Security Header, e.g. `Strict-Transport-Security: max-age=10886400`
- enable HSTS for all the endpoint's subdomains using the includeSubDomains directive
- enable support for OCSP Stapling

Again, these were discovered in our app that uses your sdk, and we must fix them. I realize most will be more of a backend change on your end, and not require SDK changes.

**Comment by breedx-splk** [comment]
Hey @ber4444 . Thanks for bringing this up. Let's take these one at a time:

* `Strict-Transport-Security` header. As I understand it, this is a header returned to the client from the server. I am not aware of anything that the android sdk here could be doing differently to help facilitate this.
* HSTS `includeSubDomains` -- According to [the spec](https://www.rfc-editor.org/rfc/rfc6797#section-6.1.2), this also looks like part of the server response headers. Seems like it instructs the client to also use strict transport security for `us0.signalfx.com` and finally `rum-ingest.us0.signalfx.com`. Seems like that makes sense, but again, what can the client do here to help?
* OCSP stapling -- a new concept to me, but seem to me like a server-side responsibility around certificate handling. 

I think the best bet is for you to open a support ticket and/or feature request through your Splunk account team. 

Please feel free to reopen if you have additional thoughts that might impact the mobile side of things here. Thanks again.
