### ISSUE TITLE
Network monitoring of HTTP calls made by third party SDK

### ISSUE THREAD

**Issue by mikaelreiersolmoen** [signalfx/splunk-otel-android#910]
We have an app where part of it is delivered by a third party SDK. The SDK includes UI, networking etc. We would like to monitor network requests made by the SDK. We currently don't have the option to configure the HTTP-client that the SDK uses, and it is not an option for the third party SDK to also integrate the Splunk RUM agent.

Is there any way to achieve this?

With the Splunk RUM agent for iOS we seem to get this behavior out of the box.

**Comment by breedx-splk** [comment]
Hi @mikaelreiersolmoen, thanks for raising this. It's not surprising that you may see some differences in behavior between iOS and Android -- they are very different platforms with different features.

What is the 3rd party SDK? Do you know what http client library it uses underneath? Do you know if that SDK supports any kind of tracing out of the box? 

If that SDK doesn't provide any means of configuring or wrapping the http client, it may not be possible.

**Comment by mikaelreiersolmoen** [comment]
Thanks for the feedback @breedx-splk. It is a custom SDK made specifically for us. Just wanted to make sure there was nothing I could do without requiring changes to the SDK. But I assume they use OkHttp, so we should be able to figure it out. Thanks again!

**Comment by breedx-splk** [comment]
Thanks for the response @mikaelreiersolmoen. I'm going to close this as answered, but if you get progress or want to chat about this more, please feel free to reopen.
